### ISSUE TITLE
Sumarize penalty points at penalty history 

### ISSUE THREAD

**Issue by valdife** [SebaProgramista/DiscordBot#1]
Like this:
![image](https://user-images.githubusercontent.com/46005237/199532383-a8a781ab-bac3-4a82-8186-7bf41e512ffb.png)

**Comment by SebaProgramista** [comment]
**Added**
![image](https://user-images.githubusercontent.com/91561361/200191714-8d18deba-99b3-4436-af1c-d3697a1a5a28.png)
