### ISSUE TITLE
Random team generator for tournaments

### ISSUE THREAD

**Issue by valdife** [SebaProgramista/DiscordBot#8]
Input: 10 players
Output: 2x teams 5 players each, pseudo-randomly selected

Can be merged with
_Make bot having events management functionality_: [https://github.com/SebaProgramista/DiscordBot/issues/7](url)

**Comment by SebaProgramista** [comment]
Done
![image](https://user-images.githubusercontent.com/91561361/200654230-29509d6e-4d6c-4e04-b687-143965b90e8e.png)
